### PR TITLE
linux: latest: update Radxa ROCK Pi 4C+ support

### PR DESCRIPTION
**Pull request by RadxaNaoki**
I'll add wifi, bluetooth and led

### CODE REVIEW

**Comment by knro** [comment]
Great, any ETA when this PR shall be merged?

**Comment by knro** [comment]
Thanks @RadxaNaoki . If this PR is merged, then we can build a minimal image with 5.19+ kernel for the Rock PI C Plus?

**Comment by RadxaNaoki** [comment]
> Thanks @RadxaNaoki . If this PR is merged, then we can build a minimal image with 5.19+ kernel for the Rock PI C Plus?

you can build 6.0 based kernel by

```
$ ./bsp linux latest
```

**Comment by knro** [comment]
@RadxaNaoki Thanks, and this now *fully* supports Rock PI 4 C Plus. How about CM3? also fully supported?

**Comment by RadxaYuntian** [comment]
Linux latest is bumped to 6.1-rc1 which included the promised ROCK 4C+ support.

**Comment by RadxaYuntian** [comment]
Currently you have to build a custom image to get all of those. However, Armbian should be able to meet those requirements soon as 4C+ support is merged.

**Pull request merged**
