### PR TITLE
refactor: remove rk3588s' obsolete patch

### PR DESCRIPTION
**Pull request by nascs**
radxa/u-boot/pull/109

### CODE REVIEW

**Review by RadxaYuntian — CHANGES_REQUESTED** [review]
这两个都没有target你现在开发的分支，改了会无法启动。
更新你本地分支，然后看看rk2410是不是需要更改

**Comment by nascs** [comment]
> 这两个都没有target你现在开发的分支，改了会无法启动。 更新你本地分支，然后看看rk2410是不是需要更改

Patchset 0010-backport has been applied.
Applying: rockchip: move crypto functions to rk3588s
Checking patch arch/arm/dts/rk3588.dtsi...
error: while searching for:
                status = "disabled";
        };

        crypto: crypto@fe370000 {
                compatible = "rockchip,rk3588-crypto";
                reg = <0x0 0xfe370000 0x0 0x4000>;
                clocks = <&scmi_clk SCMI_CRYPTO_CORE>, <&scmi_clk SCMI_CRYPTO_PKA>;
                clock-names = "sclk_crypto", "apkclk_crypto";
                clock-frequency = <350000000>, <350000000>;
                status = "disabled";
        };

        rng: rng@fe378000 {
                compatible = "rockchip,trngv1";
                reg = <0x0 0xfe378000 0x0 0x200>;
                status = "disabled";
        };

        hdptxphy1: phy@fed70000 {
                compatible = "rockchip,rk3588-hdptx-phy";
                reg = <0x0 0xfed70000 0x0 0x2000>;

error: patch failed: arch/arm/dts/rk3588.dtsi:429
Checking patch arch/arm/dts/rk3588s.dtsi...
Hunk #1 succeeded at 6762 (offset 4542 lines).
Applying patch arch/arm/dts/rk3588.dtsi with 1 reject...
Rejected hunk #1.
Applied patch arch/arm/dts/rk3588s.dtsi cleanly.
Patch failed at 0001 rockchip: move crypto functions to rk3588s
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
bsp

**Comment by RadxaYuntian** [comment]
你这是你自己现在的cm5分支吧？我们rk2410都编过启动器了啊。

**Comment by nascs** [comment]
> 你这是你自己现在的cm5分支吧？我们rk2410都编过启动器了啊。

对，这个报错是 rk3588s.dtsi 和 kernel 同步之后才有的

**Pull request closed without merging**
